/* ── i18n.js — Full translations for Jathagam app ────────────────────── */
'use strict';

const TRANSLATIONS = {
  en: {
    appName: 'Jathagam',
    tagline: 'Your Complete Vedic Birth Chart',
    generateBtn: 'Generate Chart',
    downloadPDF: 'Download PDF',
    shareBtn: 'Share Chart',
    premiumBtn: 'Unlock Premium — ₹99',
    form: {
      nameLabel: 'Full Name',
      namePlaceholder: 'Enter your full name',
      dobLabel: 'Date of Birth',
      tobLabel: 'Time of Birth',
      pobLabel: 'Birth Place',
      pobPlaceholder: 'Type city name…',
      genderLabel: 'Gender',
      male: 'Male', female: 'Female', other: 'Other',
      unknownTime: "Don't know time",
      unknownTimeNote: "We'll use 12:00 noon. Lagna may be inaccurate.",
      submitBtn: 'Generate Jathagam / ஜாதகம் உருவாக்கு',
    },
    nav: { edit: 'Edit Details', share: 'Share', unlock: 'Unlock Premium' },
    planets: {
      Sun:'Sun', Moon:'Moon', Mars:'Mars', Mercury:'Mercury',
      Jupiter:'Jupiter', Venus:'Venus', Saturn:'Saturn',
      Rahu:'Rahu', Ketu:'Ketu', Lagna:'Ascendant'
    },
    rasis: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
    rasiSymbols: ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'],
    houses: ['1st House','2nd House','3rd House','4th House','5th House','6th House','7th House','8th House','9th House','10th House','11th House','12th House'],
    nakshatras: ['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishtha','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'],
    nakLords: ['Ketu','Venus','Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury','Ketu','Venus','Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury','Ketu','Venus','Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury'],
    sections: {
      rasiChart: 'Rasi Chart', navamsaChart: 'Navamsa Chart (D9)',
      dashaTitle: 'Vimshottari Dasha', doshaTitle: 'Dosha Analysis',
      ashtakavargaTitle: 'Ashtakavarga', planetTable: 'Planetary Positions',
      nakDetails: 'Nakshatra Details', shareTitle: 'Share Your Chart',
    },
    dasha: {
      mahadasha: 'Mahadasha', antardasha: 'Antardasha', pratyantar: 'Pratyantar',
      currentPeriod: 'Current Period', starts: 'Starts', ends: 'Ends',
      years: 'years', of: 'of',
    },
    doshas: {
      mangalDosha: 'Mangal Dosha', kalaSarpa: 'Kala Sarpa Dosha',
      sadeSati: 'Sade Sati', pitraDosha: 'Pitra Dosha',
      guruChandala: 'Guru Chandala', grahanYoga: 'Grahan Yoga',
    },
    doshaStatus: { present:'Present', cancelled:'Cancelled', clear:'Clear', partial:'Partial' },
    table: { planet:'Planet', rasi:'Rasi', degree:'Degree', nakshatra:'Nakshatra', pada:'Pada', lord:'Lord', retro:'Retro' },
    planet_status: { exalted:'Exalted', debilitated:'Debilitated', retrograde:'Retrograde' },
    premium: { locked:'Premium Feature', unlockMsg:'Unlock full chart for just ₹99', unlocked:'✓ Premium Active' },
    share: { copyLink:'Copy Link', whatsapp:'WhatsApp', savePNG:'Save PNG', savePDF:'Save PDF', copied:'Link copied!', generated:'Generated by Jathagam.app' },
    tabs: { rasiChart:'Rasi Chart', planets:'Planets', nakshatra:'Nakshatra', dasha:'Dasha', dosha:'Dosha', ashtak:'Ashtakavarga', share:'Share' },
    time: { unknown:'Time not known', noon:'(Noon chart)' },
  },

  ta: {
    appName: 'ஜாதகம்',
    tagline: 'உங்கள் முழுமையான வேத ஜனன ஜாதகம்',
    generateBtn: 'ஜாதகம் உருவாக்கு',
    downloadPDF: 'PDF பதிவிறக்கம்',
    shareBtn: 'பகிர்',
    premiumBtn: 'பிரீமியம் திறக்கவும் — ₹99',
    form: {
      nameLabel: 'முழு பெயர்',
      namePlaceholder: 'உங்கள் பெயரை உள்ளிடவும்',
      dobLabel: 'பிறந்த தேதி',
      tobLabel: 'பிறந்த நேரம்',
      pobLabel: 'பிறந்த ஊர்',
      pobPlaceholder: 'நகர பெயரை தட்டச்சு செய்யவும்…',
      genderLabel: 'பாலினம்',
      male: 'ஆண்', female: 'பெண்', other: 'மற்றவை',
      unknownTime: 'நேரம் தெரியாது',
      unknownTimeNote: 'மதிய 12:00 பயன்படுத்துவோம். லக்கினம் சரியாக இருக்காது.',
      submitBtn: 'ஜாதகம் உருவாக்கு',
    },
    nav: { edit: 'திருத்து', share: 'பகிர்', unlock: 'பிரீமியம் திறக்கவும்' },
    planets: {
      Sun:'சூரியன்', Moon:'சந்திரன்', Mars:'செவ்வாய்', Mercury:'புதன்',
      Jupiter:'குரு', Venus:'சுக்ரன்', Saturn:'சனி',
      Rahu:'ராகு', Ketu:'கேது', Lagna:'லக்கினம்'
    },
    rasis: ['மேஷம்','ரிஷபம்','மிதுனம்','கடகம்','சிம்மம்','கன்னி','துலாம்','விருச்சிகம்','தனுசு','மகரம்','கும்பம்','மீனம்'],
    rasiSymbols: ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'],
    houses: ['1ஆம் வீடு','2ஆம் வீடு','3ஆம் வீடு','4ஆம் வீடு','5ஆம் வீடு','6ஆம் வீடு','7ஆம் வீடு','8ஆம் வீடு','9ஆம் வீடு','10ஆம் வீடு','11ஆம் வீடு','12ஆம் வீடு'],
    nakshatras: ['அஸ்வினி','பரணி','கிருத்திகை','ரோகிணி','மிருகசீரிஷம்','ஆருத்ரா','புனர்பூசம்','பூசம்','ஆயில்யம்','மகம்','பூரம்','உத்திரம்','அஸ்தம்','சித்திரை','சுவாதி','விசாகம்','அனுஷம்','கேட்டை','மூலம்','பூராடம்','உத்திராடம்','திருவோணம்','அவிட்டம்','சதயம்','பூரட்டாதி','உத்திரட்டாதி','ரேவதி'],
    nakLords: ['கேது','சுக்ரன்','சூரியன்','சந்திரன்','செவ்வாய்','ராகு','குரு','சனி','புதன்','கேது','சுக்ரன்','சூரியன்','சந்திரன்','செவ்வாய்','ராகு','குரு','சனி','புதன்','கேது','சுக்ரன்','சூரியன்','சந்திரன்','செவ்வாய்','ராகு','குரு','சனி','புதன்'],
    sections: {
      rasiChart: 'ராசி சார்ட்', navamsaChart: 'நவாம்சம் (D9)',
      dashaTitle: 'விம்சோத்தரி தசை', doshaTitle: 'தோஷ ஆய்வு',
      ashtakavargaTitle: 'அஷ்டகவர்க்கம்', planetTable: 'கிரக நிலைகள்',
      nakDetails: 'நட்சத்திர விவரங்கள்', shareTitle: 'ஜாதகம் பகிர்',
    },
    dasha: {
      mahadasha: 'மகாதசை', antardasha: 'அந்தர்தசை', pratyantar: 'பிரத்யந்தர்',
      currentPeriod: 'தற்போதைய காலம்', starts: 'தொடங்கும்', ends: 'முடியும்',
      years: 'ஆண்டுகள்', of: 'இன்',
    },
    doshas: {
      mangalDosha: 'செவ்வாய் தோஷம்', kalaSarpa: 'கால சர்ப தோஷம்',
      sadeSati: 'சாடேசாட்டி', pitraDosha: 'பித்ரு தோஷம்',
      guruChandala: 'குரு சண்டால யோகம்', grahanYoga: 'கிரக யோகம்',
    },
    doshaStatus: { present:'உள்ளது', cancelled:'நீக்கப்பட்டது', clear:'இல்லை', partial:'பாதி' },
    table: { planet:'கிரகம்', rasi:'ராசி', degree:'பாகை', nakshatra:'நட்சத்திரம்', pada:'பாதம்', lord:'அதிபதி', retro:'வக்ரம்' },
    planet_status: { exalted:'உச்சம்', debilitated:'நீசம்', retrograde:'வக்ரம்' },
    premium: { locked:'பிரீமியம் அம்சம்', unlockMsg:'வெறும் ₹99 க்கு முழு ஜாதகம் திறக்கவும்', unlocked:'✓ பிரீமியம் செயலில் உள்ளது' },
    share: { copyLink:'இணைப்பு நகலெடு', whatsapp:'வாட்ஸ்அப்', savePNG:'PNG சேமி', savePDF:'PDF சேமி', copied:'நகலெடுக்கப்பட்டது!', generated:'Jathagam.app மூலம் உருவாக்கப்பட்டது' },
    tabs: { rasiChart:'ராசி சட்டம்', planets:'கிரகங்கள்', nakshatra:'நட்சத்திரம்', dasha:'தசை', dosha:'தோஷம்', ashtak:'அஷ்டகவர்க்கம்', share:'பகிர்' },
    time: { unknown:'நேரம் தெரியாது', noon:'(மதிய ஜாதகம்)' },
  },

  hi: {
    appName: 'जन्म कुंडली',
    tagline: 'आपकी पूर्ण वैदिक जन्म कुंडली',
    generateBtn: 'कुंडली बनाएं',
    downloadPDF: 'PDF डाउनलोड',
    shareBtn: 'शेयर करें',
    premiumBtn: 'प्रीमियम अनलॉक करें — ₹99',
    form: {
      nameLabel: 'पूरा नाम',
      namePlaceholder: 'अपना पूरा नाम दर्ज करें',
      dobLabel: 'जन्म तिथि',
      tobLabel: 'जन्म समय',
      pobLabel: 'जन्म स्थान',
      pobPlaceholder: 'शहर का नाम टाइप करें…',
      genderLabel: 'लिंग',
      male: 'पुरुष', female: 'महिला', other: 'अन्य',
      unknownTime: 'समय नहीं पता',
      unknownTimeNote: 'हम 12:00 दोपहर का उपयोग करेंगे। लग्न सटीक न हो।',
      submitBtn: 'कुंडली बनाएं',
    },
    nav: { edit: 'बदलें', share: 'शेयर', unlock: 'प्रीमियम अनलॉक' },
    planets: {
      Sun:'सूर्य', Moon:'चंद्र', Mars:'मंगल', Mercury:'बुध',
      Jupiter:'गुरु', Venus:'शुक्र', Saturn:'शनि',
      Rahu:'राहु', Ketu:'केतु', Lagna:'लग्न'
    },
    rasis: ['मेष','वृष','मिथुन','कर्क','सिंह','कन्या','तुला','वृश्चिक','धनु','मकर','कुंभ','मीन'],
    rasiSymbols: ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'],
    houses: ['प्रथम भाव','द्वितीय भाव','तृतीय भाव','चतुर्थ भाव','पंचम भाव','षष्ठ भाव','सप्तम भाव','अष्टम भाव','नवम भाव','दशम भाव','एकादश भाव','द्वादश भाव'],
    nakshatras: ['अश्विनी','भरणी','कृत्तिका','रोहिणी','मृगशिरा','आर्द्रा','पुनर्वसु','पुष्य','आश्लेषा','मघा','पूर्व फाल्गुनी','उत्तर फाल्गुनी','हस्त','चित्रा','स्वाती','विशाखा','अनुराधा','ज्येष्ठा','मूल','पूर्वाषाढ़','उत्तराषाढ़','श्रवण','धनिष्ठा','शतभिषा','पूर्व भाद्रपद','उत्तर भाद्रपद','रेवती'],
    nakLords: ['केतु','शुक्र','सूर्य','चंद्र','मंगल','राहु','गुरु','शनि','बुध','केतु','शुक्र','सूर्य','चंद्र','मंगल','राहु','गुरु','शनि','बुध','केतु','शुक्र','सूर्य','चंद्र','मंगल','राहु','गुरु','शनि','बुध'],
    sections: {
      rasiChart: 'राशि चक्र', navamsaChart: 'नवांश कुंडली (D9)',
      dashaTitle: 'विंशोत्तरी दशा', doshaTitle: 'दोष विश्लेषण',
      ashtakavargaTitle: 'अष्टकवर्ग', planetTable: 'ग्रह स्थिति',
      nakDetails: 'नक्षत्र विवरण', shareTitle: 'कुंडली शेयर करें',
    },
    dasha: {
      mahadasha: 'महादशा', antardasha: 'अंतर्दशा', pratyantar: 'प्रत्यंतर',
      currentPeriod: 'वर्तमान काल', starts: 'प्रारंभ', ends: 'समाप्ति',
      years: 'वर्ष', of: 'का',
    },
    doshas: {
      mangalDosha: 'मंगल दोष', kalaSarpa: 'काल सर्प दोष',
      sadeSati: 'साढ़े साती', pitraDosha: 'पितृ दोष',
      guruChandala: 'गुरु चांडाल योग', grahanYoga: 'ग्रहण योग',
    },
    doshaStatus: { present:'है', cancelled:'खंडित', clear:'नहीं', partial:'आंशिक' },
    table: { planet:'ग्रह', rasi:'राशि', degree:'अंश', nakshatra:'नक्षत्र', pada:'पाद', lord:'स्वामी', retro:'वक्री' },
    planet_status: { exalted:'उच्च', debilitated:'नीच', retrograde:'वक्री' },
    premium: { locked:'प्रीमियम सुविधा', unlockMsg:'केवल ₹99 में पूर्ण कुंडली अनलॉक करें', unlocked:'✓ प्रीमियम सक्रिय' },
    share: { copyLink:'लिंक कॉपी करें', whatsapp:'व्हाट्सऐप', savePNG:'PNG सेव', savePDF:'PDF सेव', copied:'लिंक कॉपी हो गया!', generated:'Jathagam.app द्वारा निर्मित' },
    tabs: { rasiChart:'राशि चक्र', planets:'ग्रह', nakshatra:'नक्षत्र', dasha:'दशा', dosha:'दोष', ashtak:'अष्टकवर्ग', share:'शेयर' },
    time: { unknown:'समय अज्ञात', noon:'(दोपहर कुंडली)' },
  },

  te: {
    appName: 'జాతకం',
    tagline: 'మీ పూర్తి వైదిక జన్మ పత్రిక',
    generateBtn: 'జాతకం తయారుచేయి',
    downloadPDF: 'PDF డౌన్లోడ్',
    shareBtn: 'పంచుకో',
    premiumBtn: 'ప్రీమియం అన్‌లాక్ — ₹99',
    form: {
      nameLabel: 'పూర్తి పేరు',
      namePlaceholder: 'మీ పేరు నమోదు చేయండి',
      dobLabel: 'జన్మ తేదీ',
      tobLabel: 'జన్మ సమయం',
      pobLabel: 'జన్మ స్థలం',
      pobPlaceholder: 'నగరం పేరు టైప్ చేయండి…',
      genderLabel: 'లింగం',
      male: 'పురుషుడు', female: 'స్త్రీ', other: 'ఇతరులు',
      unknownTime: 'సమయం తెలియదు',
      unknownTimeNote: 'మేము మధ్యాహ్నం 12:00 ఉపయోగిస్తాం. లగ్నం సరికాకపోవచ్చు.',
      submitBtn: 'జాతకం తయారుచేయి',
    },
    nav: { edit: 'మార్చు', share: 'పంచుకో', unlock: 'ప్రీమియం అన్‌లాక్' },
    planets: {
      Sun:'సూర్యుడు', Moon:'చంద్రుడు', Mars:'కుజుడు', Mercury:'బుధుడు',
      Jupiter:'గురువు', Venus:'శుక్రుడు', Saturn:'శని',
      Rahu:'రాహువు', Ketu:'కేతువు', Lagna:'లగ్నం'
    },
    rasis: ['మేషం','వృషభం','మిథునం','కర్కాటకం','సింహం','కన్య','తుల','వృశ్చికం','ధనుస్సు','మకరం','కుంభం','మీనం'],
    rasiSymbols: ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'],
    houses: ['1వ భావం','2వ భావం','3వ భావం','4వ భావం','5వ భావం','6వ భావం','7వ భావం','8వ భావం','9వ భావం','10వ భావం','11వ భావం','12వ భావం'],
    nakshatras: ['అశ్విని','భరణి','కృత్తిక','రోహిణి','మృగశిర','ఆర్ద్ర','పునర్వసు','పుష్యమి','ఆశ్లేష','మఘ','పూర్వ ఫల్గుణి','ఉత్తర ఫల్గుణి','హస్త','చిత్ర','స్వాతి','విశాఖ','అనూరాధ','జ్యేష్ఠ','మూల','పూర్వాషాఢ','ఉత్తరాషాఢ','శ్రవణం','ధనిష్ఠ','శతభిష','పూర్వ భాద్రపద','ఉత్తర భాద్రపద','రేవతి'],
    nakLords: ['కేతు','శుక్ర','సూర్య','చంద్ర','కుజ','రాహు','గురు','శని','బుధ','కేతు','శుక్ర','సూర్య','చంద్ర','కుజ','రాహు','గురు','శని','బుధ','కేతు','శుక్ర','సూర్య','చంద్ర','కుజ','రాహు','గురు','శని','బుధ'],
    sections: {
      rasiChart: 'రాశి చక్రం', navamsaChart: 'నవాంశం (D9)',
      dashaTitle: 'వింశోత్తరి దశ', doshaTitle: 'దోష విశ్లేషణ',
      ashtakavargaTitle: 'అష్టకవర్గం', planetTable: 'గ్రహ స్థానాలు',
      nakDetails: 'నక్షత్ర వివరాలు', shareTitle: 'జాతకం పంచుకోండి',
    },
    dasha: {
      mahadasha: 'మహాదశ', antardasha: 'అంతర్దశ', pratyantar: 'ప్రత్యంతర్',
      currentPeriod: 'ప్రస్తుత కాలం', starts: 'మొదలు', ends: 'ముగింపు',
      years: 'సంవత్సరాలు', of: 'యొక్క',
    },
    doshas: {
      mangalDosha: 'కుజ దోషం', kalaSarpa: 'కాల సర్ప దోషం',
      sadeSati: 'సాడేసాటి', pitraDosha: 'పిత్రు దోషం',
      guruChandala: 'గురు చండాల యోగం', grahanYoga: 'గ్రహణ యోగం',
    },
    doshaStatus: { present:'ఉంది', cancelled:'రద్దైంది', clear:'లేదు', partial:'పాక్షికం' },
    table: { planet:'గ్రహం', rasi:'రాశి', degree:'అంశం', nakshatra:'నక్షత్రం', pada:'పాదం', lord:'అధిపతి', retro:'వక్ర' },
    planet_status: { exalted:'ఉచ్చ', debilitated:'నీచ', retrograde:'వక్ర' },
    premium: { locked:'ప్రీమియం ఫీచర్', unlockMsg:'కేవలం ₹99 కి పూర్తి జాతకం అన్‌లాక్ చేయండి', unlocked:'✓ ప్రీమియం యాక్టివ్' },
    share: { copyLink:'లింక్ కాపీ', whatsapp:'వాట్సాప్', savePNG:'PNG సేవ్', savePDF:'PDF సేవ్', copied:'లింక్ కాపీ అయింది!', generated:'Jathagam.app ద్వారా తయారైంది' },
    tabs: { rasiChart:'రాశి చక్రం', planets:'గ్రహాలు', nakshatra:'నక్షత్రం', dasha:'దశ', dosha:'దోషం', ashtak:'అష్టకవర్గం', share:'పంచుకో' },
    time: { unknown:'సమయం తెలియదు', noon:'(మధ్యాహ్నం జాతకం)' },
  }
};

/* ── Language switcher ────────────────────────────────────────────────── */
let currentLang = localStorage.getItem('jathagamLang') || 'ta';

/** Dot-notation key lookup. e.g. t('planets.Sun') */
function t(key) {
  const keys = key.split('.');
  let val = TRANSLATIONS[currentLang];
  for (const k of keys) {
    if (val === undefined || val === null) return key;
    val = val[k];
  }
  return val !== undefined ? val : (TRANSLATIONS['en'][keys[0]]?.[keys[1]] ?? key);
}

/** Set active language and re-render [data-i18n] elements */
function setLanguage(lang) {
  if (!TRANSLATIONS[lang]) return;
  currentLang = lang;
  localStorage.setItem('jathagamLang', lang);
  document.documentElement.lang = lang;
  // Update font
  if (lang === 'ta') {
    document.body.style.fontFamily = "'Noto Sans Tamil', 'Mukta', sans-serif";
  } else if (lang === 'te') {
    document.body.style.fontFamily = "'Noto Sans Telugu', 'Mukta', sans-serif";
  } else {
    document.body.style.fontFamily = "'Mukta', sans-serif";
  }
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = t(el.dataset.i18n);
    if (typeof v === 'string') el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const v = t(el.dataset.i18nPh);
    if (typeof v === 'string') el.setAttribute('placeholder', v);
  });
  // update lang buttons
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

/** Convenience: get rasi name in current lang */
function rasiName(rasiNum) { return TRANSLATIONS[currentLang].rasis[rasiNum] || TRANSLATIONS['en'].rasis[rasiNum]; }

/** Convenience: get nakshatra name in current lang */
function nakName(nakIdx) { return TRANSLATIONS[currentLang].nakshatras[nakIdx] || TRANSLATIONS['en'].nakshatras[nakIdx]; }

/** Convenience: get planet name in current lang */
function planetName(key) { return (TRANSLATIONS[currentLang].planets[key] || key); }
