/**
 * share.js — URL encoding/decoding and share panel rendering.
 * Uses LZString compression + btoa for compact URLs.
 * LZString fallback: if not loaded, uses plain JSON+btoa.
 */
'use strict';

/* ── Encode/Decode ────────────────────────────────────────────────────── */
/**
 * Encode birth data into a compact URL-safe string.
 * @param {Object} data { n, d, t, lat, lon, g, l, tz }
 * @returns {string}
 */
function encodeShareData(data) {
  const json = JSON.stringify(data);
  try {
    // Prefer LZString (loaded from CDN) for shorter URLs
    if (window.LZString) {
      return window.LZString.compressToEncodedURIComponent(json);
    }
  } catch (_) {}
  // Fallback: base64
  return btoa(encodeURIComponent(json));
}

/**
 * Decode URL parameter back to birth data object.
 * @param {string} encoded
 * @returns {Object|null}
 */
function decodeShareData(encoded) {
  if (!encoded) return null;
  try {
    if (window.LZString) {
      const dec = window.LZString.decompressFromEncodedURIComponent(encoded);
      if (dec) return JSON.parse(dec);
    }
  } catch (_) {}
  try {
    return JSON.parse(decodeURIComponent(atob(encoded)));
  } catch (_) {
    return null;
  }
}

/** Build full share URL from current birth data */
function getShareURL(data) {
  const encoded = encodeShareData(data);
  const base    = window.location.origin + '/chart.html';
  return `${base}?d=${encoded}`;
}

/** Read birth data from current URL */
function getBirthDataFromURL() {
  const params = new URLSearchParams(window.location.search);
  const d = params.get('d');
  return decodeShareData(d);
}

/* ── Share panel (Prompt 21) ──────────────────────────────────────────── */
/**
 * Render the share panel.
 * @param {Object} chartData { name, dob, tob, city, lagnaRasi, planets, currentDasha }
 * @param {string} containerId
 * @param {boolean} isPremium
 */
function renderSharePanel(chartData, containerId, isPremium) {
  const container = document.getElementById(containerId);
  if (!container) return;

  // Use the already-encoded URL param directly to avoid double-encoding
  const encodedParam = chartData.encoded || encodeShareData(chartData);
  const shareURL = `${window.location.origin}/chart.html?d=${encodedParam}`;

  const moonPlanet = chartData.planets?.find(p => p.name === 'Moon') || {};
  const sunPlanet  = chartData.planets?.find(p => p.name === 'Sun')  || {};
  const lagnaStr   = rasiName(chartData.lagnaRasi);
  const moonStr    = rasiName(moonPlanet.rasiNum);
  const sunStr     = rasiName(sunPlanet.rasiNum);
  const dashaStr   = chartData.currentDasha
    ? `${planetName(chartData.currentDasha.mahaLord)} - ${planetName(chartData.currentDasha.antarLord)}`
    : '';

  const waMsg = encodeURIComponent(
    `🌟 My Vedic Birth Chart (Jathagam)\n` +
    `Name: ${chartData.name} | DOB: ${chartData.dob} | ${chartData.city || ''}\n` +
    `Lagna: ${lagnaStr} | Moon: ${moonStr} | Sun: ${sunStr}\n` +
    (dashaStr ? `Current Dasha: ${dashaStr}\n` : '') +
    `View full chart: ${shareURL}\n` +
    `Generated by Jathagam.app — Free Tamil Jathagam`
  );

  container.innerHTML = `
    <div class="share-grid">
      <button class="share-btn copy" onclick="window.Share.copyLink('${escHtml(shareURL)}')">
        📋 <span data-i18n="share.copyLink">${t('share.copyLink')}</span>
      </button>
      <a class="share-btn whatsapp" href="https://wa.me/?text=${waMsg}" target="_blank" rel="noopener noreferrer">
        💬 <span data-i18n="share.whatsapp">${t('share.whatsapp')}</span>
      </a>
      <button class="share-btn png" onclick="window.Share.saveAsPNG()">
        🖼 <span data-i18n="share.savePNG">${t('share.savePNG')}</span>
      </button>
      <button class="share-btn pdf" onclick="${isPremium ? "window.PDF&&window.PDF.generate()" : "window.Payment&&window.Payment.initPayment()"}">
        📄 <span data-i18n="share.savePDF">${t('share.savePDF')}</span>
        ${isPremium ? '' : ' 🔒'}
      </button>
    </div>
    <div class="share-url-box">
      <input type="text" id="shareUrlInput" value="${escHtml(shareURL)}" readonly>
      <button class="copy-icon-btn" onclick="window.Share.copyLink()" title="Copy">📋</button>
    </div>
    <div style="font-size:.75rem;color:var(--muted);margin-top:.35rem;text-align:center" data-i18n="share.generated">${t('share.generated')}</div>
  `;
}

/** Escape HTML to prevent XSS when injecting URLs into attributes */
function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** Copy link to clipboard */
function copyLink(url) {
  const input = document.getElementById('shareUrlInput');
  const target = url || (input && input.value) || window.location.href;
  if (navigator.clipboard) {
    navigator.clipboard.writeText(target).then(() => showToast(t('share.copied'), 'success'));
  } else {
    if (input) { input.select(); document.execCommand('copy'); }
    showToast(t('share.copied'), 'success');
  }
}

/** Save chart area as PNG using html2canvas */
function saveAsPNG() {
  const chartArea = document.getElementById('chart-area') || document.body;
  if (window.html2canvas) {
    const oldOverflow = chartArea.style.overflow;
    chartArea.style.overflow = 'visible';
    window.html2canvas(chartArea, { useCORS: true, scale: 2 }).then(canvas => {
      chartArea.style.overflow = oldOverflow;
      const link = document.createElement('a');
      link.download = 'jathagam.png';
      link.href = canvas.toDataURL('image/png');
      link.click();
    });
  } else {
    showToast('html2canvas not loaded', '');
  }
}

/** Toast helper */
function showToast(msg, type) {
  let toast = document.getElementById('toast');
  if (!toast) {
    toast = document.createElement('div');
    toast.id = 'toast';
    document.body.appendChild(toast);
  }
  toast.textContent = msg;
  toast.className   = `show ${type || ''}`;
  setTimeout(() => { toast.className = type || ''; }, 3000);
}

// Expose globally
window.Share = {
  encodeShareData,
  decodeShareData,
  getShareURL,
  getBirthDataFromURL,
  renderSharePanel,
  copyLink,
  saveAsPNG,
  showToast,
};

// Also expose showToast globally for other modules
window.showToast = showToast;
